module.exports = {
    options: {
        team: 'Northampton',
        colour_one: '#862633',
        colour_two: '#fbe1e6',
        colour_three: "ghostwhite",
        heading: `David's Cobblers Database`,
        sub_heading: `NTFC Programme Collection`,
        img_one_src: 'prog1a.png',
        img_two_src: 'prog2.png',
        data_points: {
            season: 'Season',
            date: 'Date',
            competition: 'Competition',
            opponent: 'Opponent',
            home_away: 'Home/Away',
            programme_got_want: 'Programme Got/Want',
            id: 'ID',
            score: 'Score',
            cup_round: 'Cup Round',
            match_notes: 'Match Notes',
            price: 'Programme Price',
            notes: 'Programme Notes',
        },
    },
    "password": process.env.password,
    "sheet_id": process.env.sheet_id,
    "type": process.env.type,
    "project_id": process.env.project_id,
    "private_key_id": process.env.private_key_id,
    "private_key": process.env.private_key,
    "client_email": process.env.client_email,
    "client_id": process.env.client_id,
    "auth_uri": process.env.auth_uri,
    "token_uri": process.env.token_uri,
    "auth_provider_x509_cert_url": process.env.auth_provider_x509_cert_url,
    "client_x509_cert_url": process.env.client_x509_cert_url
}